version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresdemo
      - POSTGRES_DB=smartbrain
    ports:
      - "5432:5432"
    networks:
      - smartbrain-network

  backend:
    build: ./backend
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/smartbrain
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db
    networks:
      - smartbrain-network

volumes:
  postgres_data:


networks:
  smartbrain-network:
    driver: bridge
